genome: NCBI-hg38
BT2_FILES:
  - gs://seq-resources/UCSC-hg19/hg19.1.bt2
  - gs://seq-resources/UCSC-hg19/hg19.2.bt2
  - gs://seq-resources/UCSC-hg19/hg19.3.bt2
  - gs://seq-resources/UCSC-hg19/hg19.4.bt2
  - gs://seq-resources/UCSC-hg19/hg19.rev.1.bt2
  - gs://seq-resources/UCSC-hg19/hg19.rev.2.bt2
BT2_IDX_PFX: seq-resources/UCSC-hg19/hg19
GENOME_FA: gs://seq-resources/UCSC-hg19/ucsc-hg19.fa.gz
GENOME_FAI: gs://seq-resources/UCSC-hg19/ucsc-hg19.fa.gz.fai
GENOME_GZI: gs://seq-resources/UCSC-hg19/ucsc-hg19.fa.gz.gzi
GENOME_BL: gs://seq-resources/UCSC-hg19/ENCFF001TDO.bed.gz
GENOME_SIZE: 2.7e9
GENOME_CHR: chr1,chr2,chr3,chr4,chr5,chr6,chr7,chr8,chr9,chr10,chr11,chr12,chr13,chr14,chr15,chr16,chr17,chr18,chr19,chr20,chr21,chr22,chrX
MAPQ_CUTOFF: 30


samples:
  JURKAT_H3K27AC_01:
    phred: 33
    input: JURKAT_WCE_01
    condition:
      - TALL
      - line
    fastq:
      r1:
        #- ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR105/004/SRR1057274/SRR1057274.fastq.gz
        - /home/mlawlor/Downloads/SRR1057274.fastq.gz
  RPMI8402_H3K27AC_01:
    phred: 33
    condition:
        - TALL
        - line
    fastq:
      r1:
        - ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR152/004/SRR1522114/SRR1522114.fastq.gz
  MOLT3_H3K27AC_01:
    phred: 33
    input: MOLT3_WCE_01
    condition:
        - TALL
        - line
    fastq:
      r1:
        - ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR160/006/SRR1603656/SRR1603656.fastq.gz
  CCRFCEM_H3K27AC_01:
    phred: 33
    input: CCRFCEM_WCE_01
    condition:
      - TALL
      - line
    fastq:
      r1:
        - ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR309/000/SRR3098550/SRR3098550.fastq.gz
  MOLT4_H3K27AC_01:
    phred: 33
    input:
    condition:
      - TALL
      - line
    fastq:
      r1:
        - ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR309/009/SRR3098559/SRR3098559.fastq.gz



input_samples:
  JURKAT_WCE_01:
    phred: 33
    fastq:
      r1:
        #- ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR105/006/SRR1057276/SRR1057276.fastq.gz
        - /home/mlawlor/Downloads/SRR1057276.fastq.gz
  MOLT3_WCE_01:
    phred: 33
      fastq:
        r1:
          - ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR160/007/SRR1603657/SRR1603657.fastq.gz
  CCRFCEM_WCE_01:
    phred: 33
      fastq:
        r1:
          - ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR424/008/SRR4245518/SRR4245518.fastq.gz
  MOLT4_WCE_01:
    phred: 33
      fastq:
        r1:
          - ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR424/002/SRR4245522/SRR4245522.fastq.gz
